### ISSUE TITLE
Long Term Road Map

### ISSUE THREAD

**Issue by chris-anderson67** [JumboCode/NorthShoreCDC#18]
# Features
## Minimum Viable Product (December)

- [x] Map showing locations of murals
- [x] Information about each mural: Photo, Artist name and city, Title, Date (month, year)
- [x] Gallery Page of the murals
- [x] Links: Social media, contact info
- [x] Button to donate to NSCDC
- [x] Deploy iOS

## Spring 2018
- [x] Deploy Android
- [x] Walking tour v1 Button to toggle path on and off
- [ ] Walking tour v2 Focus the current with prev, next buttons
--
- [x] Current Location on map
- [x] Home Page redesign
- [x] Indication to click info-windows on map
- [x] Loading indicators to the image-views
- [x] Artist bio and city in the Mural Details Page
- [x] Button to find mural on map from Mural Details Page

# Admin Portal Features
## Minimum Viable Product (December)
- [x] Login with email and password
- [x] Add artist listing
- [x] Add mural listing
- [x] View current mural listings
- [x] Delete mural

##  Spring 2018
- [x] Delete Artist
- [x] Edit Mural
- [x] Edit Artist
- [x] Style the site according to designs
